name: CI Lint

on:
  workflow_dispatch:
  push:
    branches:
      - ci-lint
  pull_request:
    branches:
      - ci-lint

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint
        run: make lint
