name: CI Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - ci-unit-tests
  pull_request:
    branches:
      - ci-unit-tests

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      VERBOSE: 1
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: make test
